name: Auto Release on Push to Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump Version and Tag
        id: bump_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          IFS='.' read -r -a version <<< "${latest_tag:-v0.0.0}"
          version[2]=$((version[2]+1))
          new_tag="${version[0]}.${version[1]}.${version[2]}"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Bump Version and Tag
        id: bump_version
        run: |
          git fetch --tags
          # Check if there are any tags, default to v0.0.0 if none are found
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r -a version <<< "${latest_tag:-v0.0.0}"
          version[2]=$((version[2]+1))
          new_tag="${version[0]}.${version[1]}.${version[2]}"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV